<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => '1',
                'title' => 'Earring drop',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/H4AhskwyR3ivFRL5Oqr2',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '6',
                'user_id' => '1',
                'ordered' => '2',
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/H4AhskwyR3ivFRL5Oqr2/x5g8FtWqaYJaKideGbMeHrDaPuqGBOHzBFwWM6Y0.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-07 12:08:59',
                'updated_at' => '2018-01-13 16:29:50',
            ),
            1 => 
            array (
                'id' => '2',
                'title' => 'Black choker',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/rKLBlNl0B8ASfMP1v3DH',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '7',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/rKLBlNl0B8ASfMP1v3DH/OfPeqn0kLqlgIvS0OII6cfbQV5J7qPBlcTlxeupT.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 15:59:04',
                'updated_at' => '2018-01-13 15:59:04',
            ),
            2 => 
            array (
                'id' => '3',
                'title' => 'Gold necklace',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '13',
                'folder' => 'products/xsYhNEYlzRWH9GoR0QfU',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '7',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/xsYhNEYlzRWH9GoR0QfU/pC3dgVaLqSUC93um5SkxTomti2i3WvoB1q6h5WiR.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:01:45',
                'updated_at' => '2018-01-13 16:01:45',
            ),
            3 => 
            array (
                'id' => '4',
                'title' => 'Moon necklace',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '13',
                'folder' => 'products/ZMvZPSnuTlsAOXAx3wEd',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '7',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/ZMvZPSnuTlsAOXAx3wEd/e5RfE7fKqf2PkgUbIaAZ4ERtBkQpe3BDHokhJ4W0.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:02:20',
                'updated_at' => '2018-01-13 16:02:20',
            ),
            4 => 
            array (
                'id' => '5',
                'title' => 'Paris bracelet',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/x5kdg6sAkZ4wbGX824qu',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '8',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/x5kdg6sAkZ4wbGX824qu/SjlVpEdraXo7QXhxVquZUwWm5kco7jysmZusebVv.jpg',
                'note' => NULL,
                'options' => NULL,
                'created_at' => '2018-01-13 16:04:38',
                'updated_at' => '2018-01-13 16:14:03',
            ),
            5 => 
            array (
                'id' => '6',
                'title' => '9 cüt sırqa',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '19',
                'folder' => 'products/dyFyRcMwNODtyswIJ8SW',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '6',
                'user_id' => '1',
                'ordered' => '1',
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/dyFyRcMwNODtyswIJ8SW/nUNXWSVmgMCEl5H8U1DUVG7XFDx5gPPHEnoxYljK.jpg',
                'note' => NULL,
                'options' => NULL,
                'created_at' => '2018-01-13 16:05:36',
                'updated_at' => '2018-01-13 16:29:50',
            ),
            6 => 
            array (
                'id' => '7',
                'title' => 'Crystal ring',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/j2FaB1MEDwJatlta1uI4',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '9',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/j2FaB1MEDwJatlta1uI4/ffX0VsLjGLADh7Bk0n9CUMK881gHAUMinHBdCSDB.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:19:33',
                'updated_at' => '2018-01-13 16:19:33',
            ),
            7 => 
            array (
                'id' => '8',
                'title' => 'Star earrings',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/3AYUjgFwVMuYVZuLuRDe',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '6',
                'user_id' => '1',
                'ordered' => '1',
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/3AYUjgFwVMuYVZuLuRDe/jx8UKat0GDAR9bY3bQ0bCg6AbhKWYWcDWkLuJkTx.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:20:36',
                'updated_at' => '2018-01-13 16:29:50',
            ),
            8 => 
            array (
                'id' => '9',
                'title' => 'Cloud earrings',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/SpJ8I4A0qfmt0WhynCA8',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '6',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/SpJ8I4A0qfmt0WhynCA8/Vt4cfAtMLWWEmOYhZDVKB0ilqdyhgpA83XJZEUi5.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:21:05',
                'updated_at' => '2018-01-13 16:21:05',
            ),
            9 => 
            array (
                'id' => '10',
                'title' => 'Rose earrings',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/4AhgKt64v12tKmLs4SLC',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '6',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/4AhgKt64v12tKmLs4SLC/upUsiRrH6nIkCOsH71ci9vw2DgSFtipwpQ5R0tKB.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:22:33',
                'updated_at' => '2018-01-13 16:22:33',
            ),
            10 => 
            array (
                'id' => '11',
                'title' => 'Ring',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/m3SLCkjB1gS7rHTWjANn',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '9',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/m3SLCkjB1gS7rHTWjANn/XzAXhFUzopHRqObXSzMzYm3kQiluAWbLJHmFYoeD.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:23:37',
                'updated_at' => '2018-01-13 16:23:37',
            ),
            11 => 
            array (
                'id' => '12',
                'title' => 'Gold necklace',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '15',
                'folder' => 'products/l4Hpw6tWaXxSjlUQPvKo',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '7',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/l4Hpw6tWaXxSjlUQPvKo/PMBq5oSDvPJM0aPO0tFbih8zCwRScLB1DwOZBoJf.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:26:09',
                'updated_at' => '2018-01-13 16:26:09',
            ),
            12 => 
            array (
                'id' => '13',
                'title' => 'Paris bracelets',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/Pj3ulpRH604UevFspPnO',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '8',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/Pj3ulpRH604UevFspPnO/XvsI5bBFC6RzxplOg0sduZKGOZnnCyUj5I8W3iQQ.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:31:28',
                'updated_at' => '2018-01-13 16:31:28',
            ),
            13 => 
            array (
                'id' => '14',
                'title' => 'DIamon necklace',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/YhyIw9jUGYWHQYMJtObX',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '7',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/YhyIw9jUGYWHQYMJtObX/df4cBfaKt4OCVjgqWaJTTIjvVMvZOuEazC9YXw30.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 16:33:50',
                'updated_at' => '2018-01-13 16:33:50',
            ),
            14 => 
            array (
                'id' => '15',
                'title' => 'Butterfly bracelet',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '10',
                'folder' => 'products/FLfRgiqBfwLmqmRxSFH3',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '8',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/FLfRgiqBfwLmqmRxSFH3/1rKG2QxtwjEuC87YW98VzwuVrr3PfmNKz2EvwQ8p.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 17:00:08',
                'updated_at' => '2018-01-13 17:00:08',
            ),
            15 => 
            array (
                'id' => '17',
                'title' => 'Moon necklace',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '15',
                'folder' => 'products/4y4foe3p6YR1D7HTVFDy',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '7',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/4y4foe3p6YR1D7HTVFDy/dh5U1qUEXhce3aORpS5zlmc65HtRIQX3bBORzxjn.jpg',
                'note' => '_shoppings_n1',
                'options' => NULL,
                'created_at' => '2018-01-13 17:02:07',
                'updated_at' => '2018-01-13 17:02:07',
            ),
            16 => 
            array (
                'id' => '18',
                'title' => 'Sneakers',
                'description' => NULL,
                'is_shown' => '1',
                'old_price' => NULL,
                'price' => '35',
                'folder' => 'products/MOBWlKwo2DOjXx8N5R3e',
                'likes' => NULL,
                'dislikes' => NULL,
                'rating' => NULL,
                'sale_percent' => NULL,
                'category_id' => '10',
                'user_id' => '1',
                'ordered' => NULL,
                'trending' => NULL,
                'images' => '[]',
                'cover_image' => 'products/MOBWlKwo2DOjXx8N5R3e/P1wK1MGEus3uOB3mEhhHLnc9DmfcIcYM6cYR3SJH.jpg',
                'note' => 'eqa_shoes',
                'options' => NULL,
                'created_at' => '2018-01-13 17:31:00',
                'updated_at' => '2018-01-13 17:31:00',
            ),
        ));
        
        
    }
}